### PR TITLE
Toggle in menu bar

### PR DESCRIPTION
**Pull request by sertonix**
This adds an option to enable or disable the `Find` tab in the menu bar.

### CODE REVIEW

**Comment by confused-Techie** [comment]
Sorry to do this to you, mind getting the recent commit in here to run some tests?

**Comment by confused-Techie** [comment]
With your permission on GitHub (EDIT Discord), I've cherry picked these commits, to run the tests and see how these PR's do on tests

**Comment by sertonix** [comment]
I think you mean Discord instead of Girhub?!

**Comment by confused-Techie** [comment]
> I think you mean Discord instead of Girhub?!

Yup got a point there, whoops

**Review by confused-Techie — APPROVED** [review]
This is a cool feature I think. And personally allows even more customization of the editor. Really I'd like to see this appear in more locations, so the editor is truly completely hackable.

So I'm happy merging this one, especially since the tests are running as we would expect.

**Pull request closed without merging**
